/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 24-abr.-2024 6:33:42 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Administrador` CASCADE
;

DROP TABLE IF EXISTS `AdministradorXHorarioLaboral` CASCADE
;

DROP TABLE IF EXISTS `AdministradorXTipoDeRecurso` CASCADE
;

DROP TABLE IF EXISTS `CalificacionRecurso` CASCADE
;

DROP TABLE IF EXISTS `CalificarReserva` CASCADE
;

DROP TABLE IF EXISTS `Caracteristicas` CASCADE
;

DROP TABLE IF EXISTS `Disponibilidad` CASCADE
;

DROP TABLE IF EXISTS `HorarioLaboral` CASCADE
;

DROP TABLE IF EXISTS `Recurso` CASCADE
;

DROP TABLE IF EXISTS `RecursoXCaracteristicas` CASCADE
;

DROP TABLE IF EXISTS `RecursoXDisponibilidad` CASCADE
;

DROP TABLE IF EXISTS `Reserva` CASCADE
;

DROP TABLE IF EXISTS `ReservaXRecurso` CASCADE
;

DROP TABLE IF EXISTS `TipoDeRecurso` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

/* Create Tables */

CREATE TABLE `Administrador`
(
	`kIDusuario` BIGINT NOT NULL,
	CONSTRAINT `PK_Administrador` PRIMARY KEY (`kIDusuario` ASC)
)

;

CREATE TABLE `AdministradorXHorarioLaboral`
(
	`kIdHorarioLavoral` INT NOT NULL,
	`kIDusuario` BIGINT NOT NULL,
	CONSTRAINT `PK_Poseer` PRIMARY KEY (`kIdHorarioLavoral` ASC, `kIDusuario` ASC)
)

;

CREATE TABLE `AdministradorXTipoDeRecurso`
(
	`kIDusuario` BIGINT NOT NULL,
	`kIdTipoRecurso` INT NOT NULL,
	CONSTRAINT `PK_Gestionar` PRIMARY KEY (`kIDusuario` ASC, `kIdTipoRecurso` ASC)
)

;

CREATE TABLE `CalificacionRecurso`
(
	`kIdCalificacion` INT NOT NULL,
	`nEstadoCalificacionRecurso` SMALLINT NOT NULL,
	`kIDusuario` BIGINT NOT NULL,
	`kIdRecurso` INT NOT NULL,
	CONSTRAINT `PK_Calificacion` PRIMARY KEY (`kIdCalificacion` ASC)
)

;

CREATE TABLE `CalificarReserva`
(
	`kIdCalificarReserva` INT NOT NULL,
	`nEstadoCalificacionReserva` SMALLINT NOT NULL,
	`kIDusuario` BIGINT NOT NULL,
	`kIdReserva` BIGINT NOT NULL,
	CONSTRAINT `PK_Calificar_Resrva` PRIMARY KEY (`kIdCalificarReserva` ASC)
)

;

CREATE TABLE `Caracteristicas`
(
	`kIdCaracteristicas` INT NOT NULL,
	`nDescripcionCaracteristica` VARCHAR(255) NOT NULL,
	CONSTRAINT `PK_Caracteristicas` PRIMARY KEY (`kIdCaracteristicas` ASC)
)

;

CREATE TABLE `Disponibilidad`
(
	`kIdDisponibilidad` INT NOT NULL,
	`fHoraInicioDisponibilidad` TIME NOT NULL,
	`fHoraFinalDisponibilidad` TIME NOT NULL,
	`fDiaDisponibilidad` DATE NOT NULL,
	CONSTRAINT `PK_Disponibilidad` PRIMARY KEY (`kIdDisponibilidad` ASC)
)

;

CREATE TABLE `HorarioLaboral`
(
	`kIdHorarioLavoral` INT NOT NULL,
	`fHoraInicio` TIME NOT NULL,
	`fHoraFinal` TIME NOT NULL,
	`fDia` DATE NOT NULL,
	CONSTRAINT `PK_Horario_Laboral` PRIMARY KEY (`kIdHorarioLavoral` ASC)
)

;

CREATE TABLE `Recurso`
(
	`kIdRecurso` INT NOT NULL,
	`nNombreRecurso` VARCHAR(50) NOT NULL,
	`nDescripcionRecurso` VARCHAR(255) NOT NULL,
	`kIdTipoRecurso` INT NOT NULL,
	`nUnidades` INT NOT NULL,
	CONSTRAINT `PK_Recurso` PRIMARY KEY (`kIdRecurso` ASC)
)

;

CREATE TABLE `RecursoXCaracteristicas`
(
	`kIdRecurso` INT NOT NULL,
	`kIdCaracteristicas` INT NOT NULL,
	CONSTRAINT `PK_Ser_Caracterisado` PRIMARY KEY (`kIdRecurso` ASC, `kIdCaracteristicas` ASC)
)

;

CREATE TABLE `RecursoXDisponibilidad`
(
	`kIdRecurso` INT NOT NULL,
	`kIdDisponibilidad` INT NOT NULL,
	CONSTRAINT `PK_Poseer` PRIMARY KEY (`kIdRecurso` ASC, `kIdDisponibilidad` ASC)
)

;

CREATE TABLE `Reserva`
(
	`kIdReserva` BIGINT NOT NULL,
	`fHoraInicioReserva` TIME NOT NULL,
	`fHoraFinalReserva` TIME NOT NULL,
	`fFechaReserva` DATE NOT NULL,
	`nEstadoReserva` VARCHAR(15) NOT NULL,
	`kIDusuario` BIGINT NOT NULL,
	CONSTRAINT `PK_Reserva` PRIMARY KEY (`kIdReserva` ASC)
)

;

CREATE TABLE `ReservaXRecurso`
(
	`kIdReserva` BIGINT NOT NULL,
	`kIdRecurso` INT NOT NULL,
	`fHora` TIME NOT NULL,
	CONSTRAINT `PK_Asignar` PRIMARY KEY (`kIdReserva` ASC, `kIdRecurso` ASC)
)

;

CREATE TABLE `TipoDeRecurso`
(
	`kIdTipoRecurso` INT NOT NULL,
	`nNombreTipoRecurso` VARCHAR(50) NOT NULL,
	`nDescripcionTipoRecurso` VARCHAR(255) NOT NULL,
	CONSTRAINT `PK_Tipo_De_Recurso` PRIMARY KEY (`kIdTipoRecurso` ASC)
)

;

CREATE TABLE `Usuario`
(
	`kIDusuario` BIGINT NOT NULL,
	`nNombre` VARCHAR(254) NOT NULL,
	`nUsuario` VARCHAR(50) NOT NULL,
	`nEmail` VARCHAR(50) NOT NULL,
	`nContraseña` VARCHAR(254) NOT NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`kIDusuario` ASC)
)
COMMENT = 'persona que interactua con la aplicacion'

;

/* Create Foreign Key Constraints */

ALTER TABLE `Administrador` 
 ADD CONSTRAINT `FK_Administrador_Usuario`
	FOREIGN KEY (`kIDusuario`) REFERENCES `Usuario` (`kIDusuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `AdministradorXHorarioLaboral` 
 ADD CONSTRAINT `FK_Poseer_Administrador`
	FOREIGN KEY (`kIDusuario`) REFERENCES `Administrador` (`kIDusuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `AdministradorXHorarioLaboral` 
 ADD CONSTRAINT `FK_Poseer_Horario_Laboral`
	FOREIGN KEY (`kIdHorarioLavoral`) REFERENCES `HorarioLaboral` (`kIdHorarioLavoral`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `AdministradorXTipoDeRecurso` 
 ADD CONSTRAINT `FK_Gestionar_Administrador`
	FOREIGN KEY (`kIDusuario`) REFERENCES `Administrador` (`kIDusuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `AdministradorXTipoDeRecurso` 
 ADD CONSTRAINT `FK_Gestionar_Tipo_De_Recurso`
	FOREIGN KEY (`kIdTipoRecurso`) REFERENCES `TipoDeRecurso` (`kIdTipoRecurso`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `CalificacionRecurso` 
 ADD CONSTRAINT `FK_Calificacion_Recurso_Recurso`
	FOREIGN KEY (`kIdRecurso`) REFERENCES `Recurso` (`kIdRecurso`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `CalificacionRecurso` 
 ADD CONSTRAINT `FK_Calificacion_Recurso_Usuario`
	FOREIGN KEY (`kIDusuario`) REFERENCES `Usuario` (`kIDusuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `CalificarReserva` 
 ADD CONSTRAINT `FK_Calificar_Resrva_Reserva`
	FOREIGN KEY (`kIdReserva`) REFERENCES `Reserva` (`kIdReserva`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `CalificarReserva` 
 ADD CONSTRAINT `FK_Calificar_Resrva_Usuario`
	FOREIGN KEY (`kIDusuario`) REFERENCES `Usuario` (`kIDusuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Recurso` 
 ADD CONSTRAINT `FK_Recurso_Tipo_De_Recurso`
	FOREIGN KEY (`kIdTipoRecurso`) REFERENCES `TipoDeRecurso` (`kIdTipoRecurso`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `RecursoXCaracteristicas` 
 ADD CONSTRAINT `FK_Ser_Caracterisado_Caracteristicas`
	FOREIGN KEY (`kIdCaracteristicas`) REFERENCES `Caracteristicas` (`kIdCaracteristicas`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `RecursoXCaracteristicas` 
 ADD CONSTRAINT `FK_Ser_Caracterisado_Recurso`
	FOREIGN KEY (`kIdRecurso`) REFERENCES `Recurso` (`kIdRecurso`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `RecursoXDisponibilidad` 
 ADD CONSTRAINT `FK_Poseer_Disponibilidad`
	FOREIGN KEY (`kIdDisponibilidad`) REFERENCES `Disponibilidad` (`kIdDisponibilidad`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `RecursoXDisponibilidad` 
 ADD CONSTRAINT `FK_Poseer_Recurso`
	FOREIGN KEY (`kIdRecurso`) REFERENCES `Recurso` (`kIdRecurso`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Reserva` 
 ADD CONSTRAINT `FK_Reserva_Usuario`
	FOREIGN KEY (`kIDusuario`) REFERENCES `Usuario` (`kIDusuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ReservaXRecurso` 
 ADD CONSTRAINT `FK_Asignar_Recurso`
	FOREIGN KEY (`kIdRecurso`) REFERENCES `Recurso` (`kIdRecurso`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ReservaXRecurso` 
 ADD CONSTRAINT `FK_Asignar_Reserva`
	FOREIGN KEY (`kIdReserva`) REFERENCES `Reserva` (`kIdReserva`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
